### ISSUE TITLE
Version is set to zero, cannot be changed

### ISSUE THREAD

**Issue by homebysix** [rtrouton/Payload-Free-Package-Creator#2]
It would be nice to customize the version number that is used when creating the package. By default, it is set to zero and cannot be changed, which causes problems when trying to create a payload-free package as an update to a previous payload-free package in Munki.

Here is the PackageInfo from a test package I created:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<pkg-info overwrite-permissions="true" relocatable="false" identifier="com.github.payload_free" postinstall-action="none" version="0" format-version="2" generator-version="InstallCmds-502 (14B25)" auth="root">
    <bundle-version/>
    <upgrade-bundle/>
    <update-bundle/>
    <atomic-update-bundle/>
    <strict-identifier/>
    <relocate/>
    <scripts>
        <postinstall file="./postinstall"/>
    </scripts>
</pkg-info>
```

Note the `version="0"` in line 2.

**Comment by rtrouton** [comment]
This issue should now be resolved by the latest release of Payload-Free Package Creator.app, which is using a different way of generating installer packages. For details on the change, please see here:

https://derflounder.wordpress.com/2015/05/21/payload-free-package-creator-app-revisited/
